// <auto-generated />
namespace PB_SN_AlesBrelih_27091327.PBSN_Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class PBSN_DB_INI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PBSN_DB_INI));
        
        string IMigrationMetadata.Id
        {
            get { return "201502042107171_PBSN_DB_INI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
